name: build-test
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-10.15
          - macos-11
        python-version:
          - '3.10'
          - '3.10.0-rc.2'
          - '3.9'
          - 'pypy-3.7'
        with-venv:
          - 'true'
          - 'false'
        with-homebrew:
          - 'true'
          - 'false'
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        if: |
          !(matrix.with-homebrew == 'true' && runner.os != 'macOS' ||
            matrix.with-homebrew == 'true' && runner.os == 'macOS' &&
            (startswith(matrix.python-version, 'pypy-') ||
             contains(matrix.python-version, '-rc') ||
             contains(matrix.python-version, '-b')
            )
           )
        with:
          python-version: ${{ matrix.python-version }}
          homebrew-python: ${{ matrix.with-homebrew }}
          with-venv: ${{ matrix.with-venv }}
          pyb-args: '--version'
  test-summary:
    if: success() || failure()
    runs-on: ubuntu-latest
    name: Test Summary
    needs: test
    steps:
      - name: Check matrix status
        if: needs.test.result != 'success'
        run: exit 1
